spring:
    application:
        name: javauser
    datasource:
        url: jdbc:h2:mem:javauser_db
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
jwt:
    secret: P38YGkkxCF218qb0LayMGrqejrg0wykm9JKDgDaVc8sivZnLeL
    expiration-ms: 86400000
validation:
    regex:
        email: ^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$
        password: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$
logging:
    level:
        root: INFO
server:
    port: 8080


